language: python
python:
- "2.6"
- "2.7"
- "3.2"
- "3.3"
- "3.4"
- "3.5"
install:
- pip install -r requirements.txt
- pip install coveralls
script: coverage run --source plantmeter ./setup.py test
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libsndfile1
after_success:
- coveralls

