language: python
python:
- "2.6"
- "2.7"
- "3.2"
- "3.3"
- "3.4"
- "3.5"
services:
- mongodb
install:
- pip install -r requirements.txt
- pip install coveralls
script: coverage run --source plantmeter ./setup.py test
after_success:
- coveralls

